DJ_diplom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from shop import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexArticle.as_view(), name='index'),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('authentication.urls', namespace='user'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authentication/urls.py
from django.contrib import admin
from django.urls import path, include
import authentication.views as auth

app_name = 'user'


urlpatterns = [
    path('signup/', auth.register, name='registration'),
    path('', include('django.contrib.auth.urls')),
]

"""
This will include the following URL patterns:

accounts/login/ [name='login']
accounts/logout/ [name='logout']
accounts/password_change/ [name='password_change']
accounts/password_change/done/ [name='password_change_done']
accounts/password_reset/ [name='password_reset']
accounts/password_reset/done/ [name='password_reset_done']
accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/reset/done/ [name='password_reset_complete']
"""

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.urls import path
from shop import views


app_name = 'shop'

urlpatterns = [

    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail')
]

authentication/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):

    name = models.CharField(max_length=50)

    slug = models.SlugField(
        max_length=50,
        unique=True
    )

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Катогории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(
            'shop:product_list_by_category',
            args=[self.slug]
        )


class Product(models.Model):

    category = models.ForeignKey(
        Category,
        related_name='products',
        on_delete=models.CASCADE
    )

    name = models.CharField(max_length=70)
    slug = models.SlugField(max_length=70)

    image = models.ImageField(
        upload_to='products/',
        blank=True,
        verbose_name='Изображение'
    )

    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(
            'shop:product_detail',
            args=[self.id, self.slug]
        )


class Article(models.Model):

    name = models.CharField(max_length=70, verbose_name='Заголовок статьи')
    text = models.CharField(max_length=1000, verbose_name='Текст статьи')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создана')
    image = models.ImageField(
        upload_to='articles/',
        blank=True,
        verbose_name='Изображение'
    )
    products = models.ManyToManyField(
        Product,
        related_name='products'
    )

    class Meta:
        ordering = ('created',)
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    def __str__(self):
        return self.name

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):
    pass

#
# class UserCreationForm(forms.Form):
#     pass

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from authentication.forms import UserCreationForm


def register(request):
    if request.method == 'POST':
        f = UserCreationForm(request.POST)
        if f.is_valid():
            f.save()
            return redirect('login')

    else:
        f = UserCreationForm()

    return render(request, 'authentication/signup.html', {'form': f})

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'override': True})
    return render(request, 'cart/detail.html', {'cart': cart})

shop/views.py
from django.shortcuts import render, get_object_or_404

from cart.forms import CartAddProductForm
from shop.models import Category, Product, Article
from django.views.generic import ListView


# def index_view(request):
#
#     articles = Article.objects.prefetch_related('products')
#
#     context = {'articles': articles}
#
#     return render(request, 'shop/index.html', context)


class IndexArticle(ListView):
    template_name = 'shop/index.html'
    model = Article
    ordering = 'created'


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    # product = get_object_or_404(Product,
    #                             id=id,
    #                             slug=slug,
    #                             available=True)

    product = Product.objects.get(id=id, slug=slug)

    cart_product_form = CartAddProductForm()

    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}Четвёрочка{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
  </head>
  <body>
    <div id="header">
      <a href="/" class="logo">Четвёрочка</a>

      <form action="/shop/">
        <input type="submit" value="Каталог товаров" />
      </form>
      {% if not user.is_authenticated %}
      <form action="/login/">
        <input type="submit" value="LOGIN" />
      </form>
      {% else %}
      <form action="/logout/">
        <input type="submit" value="LOGOUT" />
      </form>
      {% endif %}
    </div>
    <div id="subheader">

      <div class="cart">
        {% with total_items=cart|length %}
          {% if total_items > 0 %}
            Ваша корзина:
            <a href="{% url "cart:cart_detail" %}">
              товаров - {{ total_items }},
              на сумму {{ cart.get_total_price }} рублей
            </a>
          {% else %}
            Ваша корзина пуста
          {% endif %}
        {% endwith %}
      </div>
    </div>
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

shop/templates/shop/index.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}


{% for article in article_list %}
  <div align="center">
  <h2>{{article.name}}</h2> <br>
  <h4>{{ article.text }}</h4><br>
  <img src="{% if article.image %} {{ article.image.url }}
  {% else %} {% static 'img/no_image.png' %} {% endif %}" width="500"> <br>

    {% for product in article.products.all %}
    <a href="{{product.get_absolute_url}}"> <h3>{{product.name}} . . . {{ product.price }} ₽ </h3> </a>
    {% endfor %}
  </div>

{% endfor %}
{% endblock %}

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}

  <div class="product-detail">
    <img src="{{product.image.url}}">
    <h1>{{ product.name }}</h1>
    <h2>
      <a href="{{ product.category.get_absolute_url }}">
        {{ product.category }}
      </a>
    </h2>
    <p class="price">{{ product.price }} ₽</p>
    <form action="{% url "cart:cart_add" product.id %}" method="post">
      {{ cart_product_form }}
      {% csrf_token %}
      <input type="submit" value="Add to cart">
    </form>
    {{ product.description }}
  </div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar">
    <h3>Categories</h3>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url "shop:product_list" %}">All</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
    {% for product in products %}
      <div class="item">
        <a href="{{ product.get_absolute_url }}">
          <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
        <br>
        {{ product.price }} ₽
      </div>
    {% endfor %}
  </div>
{% endblock %}